'Category: Vendor':
  # Source
-   pylav/**/vendor/*
-   pylav/vendor/*
'Category: M3U Parser':
  # Source
-   pylav/extension/m3u/*
'Category: Radio':
-   pylav/extension/radio/*
'Category: CI':
-   .github/workflows/*
'Category: Lavalink':
-   pylav/nodes/*
'Category: i18n':
  # Locale files
-   pylav/**/locales/*
'Category: Filters':
  # Locale files
-   pylav/nodes/api/responses/filters/*
-   pylav/players/filters/*
'Category: Database':
  # Source
-   pylav/storage/*
'Category: Red Utils':
  # Source
-   pylav/vendor/red/*
-   pylav/extension/red/*
