ignore:
-   tests/
-   docs/
-   tools/
-   build/
-   pylav/**/vendor/**
-   pylav/vendor/**
-   .github/workflows

refactor:
    include: []
    skip:
    -   simplify-fstring-formatting
    rule_types:
    -   refactoring
    -   suggestion
    -   comment
    python_version: '3.11'

metrics:
    quality_threshold: 25.0

clone_detection:
    min_lines: 3
    min_duplicates: 2
    identical_clones_only: false

github:
    labels: ['Feat: Code Quality']
    ignore_labels:
    -   sourcery-ignore
    request_review: author
    sourcery_branch: sourcery/{base_branch}
