[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.autopep8]
max_line_length = 120
ignore = "E203,E501,W503,E402"
in-place = true
recursive = true
aggressive = 3
exclude = "pylav/_city_dump.py"

[tool.black]
line-length = 120
target-version = ['py310']
force-exclude = '''
    /(
        pylav\/vendored
    )/
    '''

[tool.isort]
profile = "black"
line_length = 120
py_version = 310
known_third_party = [
    "aiofile",
    "aiohttp",
    "aiohttp_client_cache",
    "aiopath",
    "anyio",
    "apscheduler",
    "apsw",
    "asyncpg",
    "asyncspotify",
    "asyncstdlib",
    "brotli",
    "cached_property",
    "discord",
    "deepdiff6",
    "expiringdict",
    "humanize",
    "iso8601",
    "packaging",
    "piccolo",
    "platformdirs",
    "psutil",
    "pytz",
    "yaml",
    "red_commons",
    "redis",
    "rich",
    "tabulate",
    "typing_extensions",
    "ujson",
    "uvloop"

]
known_local_folder = [
    "pylav"
]
