name: Update dev version

on:
    workflow_dispatch:

defaults:
    run:
        shell: bash
env:
    project-name: PyLav
jobs:
    bump_version:
        name: Bump release version
        runs-on: ubuntu-latest
        env:
            RELEASE_TYPE: dev
        steps:
        -   uses: actions/checkout@v3.1.0
            with:
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        -   name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.x
        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install bump2version setuptools wheel poetry
        -   name: Retrieve current version
            run: |
                echo "Current version: $(python setup.py --version)"
                echo "::set-output name=VERSION::$(python setup.py --version)"
            id: current_version
        -   name: Bump Version
            run: |
                bump2version --current-version $(poetry version --short) ${{ env.RELEASE_TYPE }}
        -   name: Retrieve new version
            run: |
                echo "::set-output name=VERSION::$(poetry version --short)"
            id: new_version
        -   name: Import GPG key
            uses: crazy-max/ghaction-import-gpg@v5
            with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                git_user_signingkey: true
                git_commit_gpgsign: true
                git_tag_gpgsign: true
            id: import_gpg
        -   name: Git Auto Commit
            uses: stefanzweifel/git-auto-commit-action@v4.15.4
            with:
                commit_message: '[skip ci]Automated version bump: v${{ steps.current_version.outputs.VERSION }} >> v${{ steps.new_version.outputs.VERSION }}'
                tagging_message: v${{ steps.new_version.outputs.VERSION }}
                commit_options: -S
                commit_user_name: ${{ steps.import_gpg.outputs.name }}
                commit_user_email: ${{ steps.import_gpg.outputs.email }}
                commit_author: ${{ steps.import_gpg.outputs.name }} <${{ steps.import_gpg.outputs.email }}>
        outputs:
            RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
            CURRENT_RELEASE: ${{ steps.current_version.outputs.VERSION }}
            NEW_RELEASE: ${{ steps.new_version.outputs.VERSION }}
